version: '2'
services:
    apprealstate-app:
        image: apprealstate
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://apprealstate-mysql:3306/apprealstate?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    apprealstate-mysql:
        extends:
            file: mysql.yml
            service: apprealstate-mysql
